"""Phase 6A public series reports against independent scientific fixtures.

These tests inspect the canonical boundary, safe JSON and Markdown, including
explicit unavailable gaps and bounded identity details. Computation remains in
the existing owners; no report expectation is generated by a renderer.
"""
from copy import deepcopy
from fractions import Fraction
import json
from pathlib import Path

import pytest
from jsonschema import Draft202012Validator

from recursive_integrity_toolkit.config import RepresentationConfig
from recursive_integrity_toolkit.io.validation import validate_bundle
from recursive_integrity_toolkit.lineage.graph import LineageLimits
from recursive_integrity_toolkit.metrics import longitudinal as series
from recursive_integrity_toolkit.models import AuditBundle, FileRole, InputSource, TailSelectionOptions
from recursive_integrity_toolkit.representations.compatibility import StateMappingDeclaration
from recursive_integrity_toolkit.representations.field import select_field_representation
from recursive_integrity_toolkit.reports.assembly import assemble_report, privacy_view
from recursive_integrity_toolkit.reports.json_report import render_json
from recursive_integrity_toolkit.reports.markdown_report import render_markdown
from recursive_integrity_toolkit.result import SECTION_ORDER, validate_report
from recursive_integrity_toolkit.utils.hashing import IdentifierProtection


ROOT = Path(__file__).resolve().parents[2]
FIXTURES = ROOT / "tests/fixtures/longitudinal"
CASES = json.loads((FIXTURES / "cases.json").read_text())["cases"]
SCHEMA = json.loads((ROOT / "schemas/report.schema.json").read_text())
SECRET = b"longitudinal-report-fixed-test-key!"
FAMILIES = {"distribution", "provenance", "direct_closure", "tail", "lineage"}


def _run():
    nullable = ("started_at", "completed_at", "duration_seconds", "python_version",
                "platform", "command", "config_hash", "random_seed")
    return {"run_id": "longitudinal-integration", "toolkit_version": "0.1.0.dev4",
            "report_schema_version": "1.2", **dict.fromkeys(nullable),
            "strict_mode": False, "redacted_mode": False, "network_call_count": 0,
            "deterministic": True, "privacy_mode": "standard", "run_status": "complete",
            "null_reasons": {name: "not_recorded" for name in nullable}}


def _case(name="observed_three_version"):
    return deepcopy(next(case for case in CASES if case["case_id"] == name))


def _load(case, tmp_path):
    tmp_path.mkdir(parents=True, exist_ok=True)
    loaded = {row["dataset_version"] for row in case["records"]}
    primary = next(version for version in reversed(case["selected_versions"]) if version in loaded)
    sources = []
    for index, version in enumerate(sorted(loaded)):
        path = tmp_path / f"records_{index}.jsonl"
        path.write_text("".join(json.dumps(row) + "\n" for row in case["records"]
                                if row["dataset_version"] == version), encoding="utf-8")
        role = (FileRole.LINEAGE_CONTEXT if version in case["context_versions"] else
                FileRole.RECORDS_PRIMARY if version == primary else FileRole.RECORDS_COMPARE)
        sources.append(InputSource(role, path))
    path = tmp_path / "provenance.jsonl"
    path.write_text("".join(json.dumps(row) + "\n" for row in case["provenance"]), encoding="utf-8")
    sources.append(InputSource(FileRole.PROVENANCE_MANIFEST, path))
    if case["order_document"] is not None:
        path = tmp_path / "order.json"
        path.write_text(json.dumps(case["order_document"]), encoding="utf-8")
        sources.append(InputSource(FileRole.VERSION_ORDER, path))
    return validate_bundle(AuditBundle(tuple(sources)))


def _declarations(case):
    loaded = {row["dataset_version"] for row in case["records"]}
    return tuple(series.SnapshotDeclaration(version, RepresentationConfig(**{
        key: value for key, value in declaration.items() if key != "state_semantics"
    }), declaration["state_semantics"], empty_scope=version not in loaded)
        for version, declaration in case["representations"].items())


def _selection(case, bundle, baseline="first", mappings=None):
    declarations = _declarations(case)
    if mappings is None:
        mappings = ()
        if case["case_id"] == "directed_many_to_one":
            earlier, later = declarations
            def descriptor(declaration):
                return select_field_representation((), dataset_versions=(declaration.dataset_version,),
                    config=declaration.representation).descriptor
            declared = case["expected_pairs"][0]["mapping"]
            mapping = StateMappingDeclaration(declared["direction"], descriptor(earlier), descriptor(later),
                earlier.state_semantics, later.state_semantics, declared["state_mapping"])
            mappings = (series.LongitudinalMapping(earlier.dataset_version, later.dataset_version, mapping),)
    return series.select_longitudinal_versions(bundle, declarations=declarations,
                                               baseline=baseline, mappings=mappings)


def _report(case, tmp_path, *, tail=False, lineage=False, limits=None, baseline="first"):
    bundle = _load(case, tmp_path)
    selection = _selection(case, bundle, baseline)
    result = series.analyze_longitudinal(bundle, selection=selection, lineage=lineage,
        lineage_limits=limits, tail_options=TailSelectionOptions("singleton_count") if tail else None)
    return assemble_report(bundle, run=_run(), longitudinal=result), result, bundle


def _checked(report):
    payload = report.to_dict()
    Draft202012Validator(SCHEMA).validate(payload)
    validate_report(payload)
    assert tuple(payload) == SECTION_ORDER
    assert payload["run"]["report_schema_version"] == "1.2"
    assert payload["capabilities"] == payload["observability"]["capabilities"]
    assert "input_signature" not in json.dumps(payload)
    assert "selection_signature" not in json.dumps(payload)
    return payload


def _fraction(actual, expected):
    if expected is None:
        assert actual is None
    else:
        assert actual == pytest.approx(float(Fraction(expected)), rel=1e-12, abs=1e-12)


def _pair_rows(payload):
    inputs = payload["inputs"]["longitudinal"]
    snapshots = {row["snapshot_id"]: row["dataset_version"] for row in inputs["snapshots"]}
    rows = {row["comparison_id"]: row for row in payload["derived_metrics"]["longitudinal"]["comparisons"]}
    return {(snapshots[pair["earlier_snapshot_id"]], snapshots[pair["later_snapshot_id"]]):
            rows[pair["comparison_id"]] for pair in inputs["comparisons"]}


def _value(row, name):
    return row[name]["value"]


@pytest.mark.parametrize("name", [case["case_id"] for case in CASES
                                  if "expected_snapshots" in case and case["case_id"] != "missing_order"])
@pytest.mark.parametrize("tail", [False, True])
def test_public_distribution_fields_match_frozen_oracles(tmp_path, name, tail):
    case = _case(name)
    report, result, _ = _report(case, tmp_path, tail=tail)
    payload = _checked(report)
    inputs = payload["inputs"]["longitudinal"]
    assert [row["dataset_version"] for row in inputs["snapshots"]] == case["selected_versions"]
    assert [row["snapshot_id"] for row in inputs["snapshots"]] == [
        f"s{index:04}" for index in range(1, len(case["selected_versions"]) + 1)]
    assert inputs["comparison_count"] == len(result.comparisons)
    observed = payload["observed_facts"]["longitudinal"]["snapshots"]
    derived = payload["derived_metrics"]["longitudinal"]["snapshots"]
    for descriptor, facts, metrics in zip(inputs["snapshots"], observed, derived, strict=True):
        oracle = case["expected_snapshots"][descriptor["dataset_version"]]
        assert facts["snapshot_id"] == metrics["snapshot_id"] == descriptor["snapshot_id"]
        for name, expected in (("record_count", "record_count"),
                               ("representation_eligible_record_count", "eligible_count"),
                               ("representation_excluded_record_count", "excluded_count")):
            assert _value(facts, name) == oracle[expected]
        assert _value(metrics, "support_size") == oracle["support_size"]
        _fraction(_value(metrics, "gini_simpson_diversity"), oracle["diversity"])
        assert facts["record_count"]["evidence_class"] == "observed_fact"
        assert facts["record_count"]["scope_id"] == descriptor["population_scope_id"]
        assert metrics["support_size"]["scope_id"] == descriptor["representation_scope_id"]
    pairs = _pair_rows(payload)
    for oracle in case["expected_pairs"]:
        row = pairs[oracle["earlier"], oracle["later"]]
        if "expected_pair_error" in oracle:
            assert row["support_delta"]["status"] == "unavailable"
            assert _value(row, "support_delta") is None
            assert "R_LONGITUDINAL_PAIR_BLOCKED" in row["support_delta"]["reason_codes"]
            continue
        expected = oracle["distribution"]
        assert _value(row, "record_count_delta") == expected["record_count_delta"]
        assert _value(row, "support_delta") == expected["support_delta"]
        _fraction(_value(row, "gini_simpson_diversity_delta"), expected["diversity_delta"])
        for name, field in (("extinct_states", "missing_states"), ("added_states", "added_states"),
                            ("retained_states", "retained_states")):
            details = _value(row, name)
            assert (None if details is None else details["items"]) == expected[field]
            if details is not None:
                assert details["total_count"] == details["returned_count"] == len(expected[field])
                assert details["omitted_count"] == 0
        tail_states = _value(row, "tail_extinct_states")
        if tail:
            assert (None if tail_states is None else tail_states["items"]) == expected["tail_extinct_states"]
        else:
            assert tail_states is None
            assert "R_LONGITUDINAL_FAMILY_NOT_REQUESTED" in row["tail_extinct_states"]["reason_codes"]
        for name in ("record_count_delta", "support_delta", "gini_simpson_diversity_delta"):
            delta = row[name]
            assert delta["scope_id"] is None and delta["denominator"] is None
            assert delta["denominator_reason"] == "not_applicable_to_difference"
            assert delta["earlier_scope_id"] and delta["later_scope_id"]
            assert "scope" not in delta and "representation" not in delta
    execution = payload["capabilities"]["dataset_longitudinal"]["longitudinal_execution"]
    assert execution["status"] == result.execution_status.value
    for row in (*execution["snapshot_statuses"], *execution["comparison_statuses"]):
        assert set(row["families"]) == FAMILIES
        assert row["families"]["lineage"]["execution_status"] == "not_requested"


def test_public_provenance_and_direct_intervals_retain_endpoint_denominators(tmp_path):
    case = _case()
    report, _, _ = _report(case, tmp_path)
    payload = _checked(report)
    for version, facts, metrics in zip(case["selected_versions"],
            payload["observed_facts"]["longitudinal"]["snapshots"],
            payload["derived_metrics"]["longitudinal"]["snapshots"], strict=True):
        expected = case["expected_provenance"][version]
        assert _value(facts, "source_type_counts") == expected["source_counts"]
        assert _value(facts, "provenance_confidence_counts") == expected["confidence_counts"]
        assert _value(facts, "missing_provenance_count") == expected["missing_provenance_count"]
        for key, value in expected["source_shares"].items():
            _fraction(_value(metrics, "source_type_shares")[key], value)
        for name, value in zip(("lower_bound", "upper_bound", "interval_width"), expected["direct_bounds"], strict=True):
            _fraction(_value(metrics, "direct_closure_" + name), value)
    pairs = _pair_rows(payload)
    for oracle in case["expected_pairs"]:
        row, expected = pairs[oracle["earlier"], oracle["later"]], oracle["provenance"]
        for suffix, value in expected["coverage_delta"].items():
            name = {"row": "provenance_row_coverage_delta", "required": "provenance_required_field_coverage_delta",
                    "grounding": "grounding_field_coverage_delta"}[suffix]
            _fraction(_value(row, name), value)
        for category, value in expected["source_share_delta"].items():
            _fraction(_value(row, "source_type_share_deltas")[category], value)
        for suffix, value in zip(("lower_bound", "upper_bound", "interval_width"), expected["direct_bounds_delta"], strict=True):
            _fraction(_value(row, "direct_closure_" + suffix + "_delta"), value)
        envelope = row["missing_provenance_share_delta"]
        assert envelope["earlier_denominator"] == case["expected_provenance"][oracle["earlier"]]["record_count"]
        assert envelope["later_denominator"] == case["expected_provenance"][oracle["later"]]["record_count"]


@pytest.mark.parametrize("name", ["lineage_complete", "lineage_partial", "lineage_zero_grounded"])
def test_public_lineage_matches_independent_targets_and_changes(tmp_path, name):
    case = _case(name)
    report, result, _ = _report(case, tmp_path, lineage=True, baseline="none")
    payload = _checked(report)
    shared = payload["observed_facts"]["longitudinal"]["shared_lineage"]
    assert shared["loaded_record_count"] == len(case["records"])
    assert shared["evidence_scope"] == "common_supplied_retrospective_graph"
    assert shared["execution_status"] == result.shared_lineage.execution_status.value
    for descriptor, facts, metrics in zip(payload["inputs"]["longitudinal"]["snapshots"],
            payload["observed_facts"]["longitudinal"]["snapshots"],
            payload["derived_metrics"]["longitudinal"]["snapshots"], strict=True):
        expected = case["expected_lineage"][descriptor["dataset_version"]]
        for field, key in (("grounded_record_count", "G"), ("closed_record_count", "C"),
                           ("unresolved_record_count", "U"), ("distinct_external_root_count", "distinct_external_root_count")):
            assert _value(metrics, field) == expected[key]
        for field, key in (("ancestry_concentration_hhi", "hhi"), ("effective_external_root_count", "effective_root_count"),
                           ("resolved_parent_edge_coverage", "resolved_reference_coverage"),
                           ("resolved_lineage_coverage", "resolved_lineage_coverage"),
                           ("external_ancestry_coverage", "external_ancestry_coverage")):
            _fraction(_value(metrics, field), expected[key])
        for field, key in (("declared_parent_reference_count", "declared_parent_references"),
                           ("resolved_parent_reference_count", "resolved_parent_references"),
                           ("unresolved_parent_reference_count", "unresolved_parent_references")):
            assert _value(facts, field) == expected[key]
        assert metrics["ancestry_concentration_hhi"]["status"] == expected["concentration_status"]
        assert metrics["ancestry_concentration_hhi"]["denominator"] == expected["G"]
    pairs = _pair_rows(payload)
    for oracle in case["expected_pairs"]:
        row, expected = pairs[oracle["earlier"], oracle["later"]], oracle["lineage"]
        for field, key in (("distinct_external_root_count_delta", "distinct_external_root_count_delta"),
                           ("ancestry_concentration_hhi_delta", "hhi_delta"),
                           ("effective_external_root_count_delta", "effective_root_count_delta")):
            _fraction(_value(row, field), expected[key])
        assert row["ancestry_concentration_hhi_delta"]["status"] == expected["concentration_delta_status"]
        assert set(expected["concentration_delta_reason_codes"]) <= set(row["ancestry_concentration_hhi_delta"]["reason_codes"])


@pytest.mark.parametrize("limits,graph_available", [(LineageLimits(max_nodes=1), False),
                                                    (LineageLimits(max_root_memberships=1), True)])
def test_public_resource_failures_preserve_independent_values_without_zero_roots(tmp_path, limits, graph_available):
    report, _, _ = _report(_case("lineage_complete"), tmp_path, lineage=True, limits=limits)
    payload = _checked(report)
    shared = payload["observed_facts"]["longitudinal"]["shared_lineage"]
    assert shared["execution_status"] == "failed"
    assert (shared["cycle_status"] is not None) is graph_available
    assert shared["resource_usage"]["exhausted_limit"] in {"max_nodes", "max_root_memberships"}
    for row in payload["derived_metrics"]["longitudinal"]["snapshots"]:
        assert _value(row, "distinct_external_root_count") is None
        assert row["distinct_external_root_count"]["status"] == "unavailable"
        assert _value(row, "support_size") is not None
    assert payload["capabilities"]["dataset_longitudinal"]["longitudinal_execution"]["status"] == "partial"


def test_unrequested_series_has_no_execution_and_explicit_empty_rows(tmp_path):
    bundle = _load(_case(), tmp_path)
    payload = _checked(assemble_report(bundle, run=_run()))
    selection = payload["inputs"]["longitudinal"]
    assert selection["requested"] is False and selection["selected_version_count"] == selection["comparison_count"] == 0
    assert selection["snapshots"] == selection["comparisons"] == selection["scopes"] == []
    assert payload["observed_facts"]["longitudinal"] == {"snapshots": [], "shared_lineage": None}
    assert payload["derived_metrics"]["longitudinal"] == {"snapshots": [], "comparisons": []}
    execution = payload["capabilities"]["dataset_longitudinal"]["longitudinal_execution"]
    assert execution["status"] == "not_requested"
    assert execution["requested_families"] == execution["snapshot_statuses"] == execution["comparison_statuses"] == []
    assert "R_LONGITUDINAL_NOT_REQUESTED" in execution["reason_codes"]


@pytest.mark.parametrize("name,max_versions,snapshot_count", [("missing_order", 100, 2),
                                                             ("observed_three_version", 2, 0)])
def test_failed_selection_retains_available_independent_snapshots(tmp_path, name, max_versions, snapshot_count):
    case = _case(name)
    bundle = _load(case, tmp_path)
    failure = series.analyze_longitudinal_failure(bundle, declarations=_declarations(case), max_versions=max_versions)
    report = assemble_report(bundle, run=_run(), longitudinal_failure=failure)
    payload = _checked(report)
    inputs = payload["inputs"]["longitudinal"]
    assert inputs["requested"] is True
    assert inputs["primary_snapshot_id"] is None and inputs["order_source"] is None
    assert inputs["comparison_count"] == 0 and inputs["comparisons"] == []
    facts = payload["observed_facts"]["longitudinal"]["snapshots"]
    assert len(facts) == snapshot_count
    if name == "missing_order":
        assert [_value(row, "record_count") for row in facts] == [1, 1]
    execution = payload["capabilities"]["dataset_longitudinal"]["longitudinal_execution"]
    assert execution["status"] == "failed"
    reason = "R_LONGITUDINAL_SELECTION_INVALID" if name == "missing_order" else "R_LONGITUDINAL_RESOURCE_LIMIT"
    assert reason in execution["reason_codes"]
    markdown = render_markdown(privacy_view(report, protection=IdentifierProtection(secret=SECRET)))
    assert 'Series execution: `"failed"`' in markdown
    assert "No comparison values were supplied" in markdown
    assert report.to_dict() == payload


def test_report_assembly_and_rendering_never_execute_series_or_graph_algorithms(tmp_path, monkeypatch):
    from recursive_integrity_toolkit.lineage import ancestry

    case = _case("lineage_complete")
    _, result, bundle = _report(case, tmp_path, lineage=True)
    def forbidden(*args, **kwargs):
        pytest.fail("report boundary executed an analytical entry point")
    for name in ("analyze_longitudinal", "calculate_state_distribution", "compare_support", "select_tail"):
        monkeypatch.setattr(series, name, forbidden)
    for name in ("build_lineage_graph", "analyze_cycles", "_resolve_roots", "analyze_selected_lineage"):
        monkeypatch.setattr(ancestry, name, forbidden)
    report = assemble_report(bundle, run=_run(), longitudinal=result)
    view = privacy_view(report, mode="redacted", protection=IdentifierProtection(secret=SECRET))
    _checked(view)
    assert render_markdown(view) and json.loads(render_json(view)) == view.to_dict()


def test_markdown_keeps_order_gaps_status_and_endpoint_scope_details(tmp_path):
    report, _, _ = _report(_case("incompatible_middle"), tmp_path)
    view = privacy_view(report, protection=IdentifierProtection(secret=SECRET))
    markdown = render_markdown(view)
    assert "### Ordered longitudinal snapshots" in markdown
    assert "### Ordered longitudinal comparisons" in markdown
    assert 'Series execution: `"partial"`' in markdown
    assert "R_LONGITUDINAL_PAIR_BLOCKED" in markdown
    assert "Unavailable (null)" in markdown
    assert "earlier_scope_id" in markdown and "later_scope_id" in markdown
    assert "observed later version under the declared representation" in markdown
    comparison_rows = [line for line in markdown.splitlines() if line.startswith('| `"p')]
    assert [row.split("|")[1].strip() for row in comparison_rows] == ['`"p0001"`', '`"p0002"`', '`"p0003"`']
    assert markdown.endswith("\n") and not markdown.endswith("\n\n")
    assert json.loads(render_json(view)) == view.to_dict()


def test_all_scheduled_pairs_blocked_is_failed_with_snapshot_values_retained(tmp_path):
    case = _case("incompatible_middle")
    report, _, _ = _report(case, tmp_path, baseline="none")
    payload = _checked(report)
    assert payload["capabilities"]["dataset_longitudinal"]["longitudinal_execution"]["status"] == "failed"
    snapshots = payload["derived_metrics"]["longitudinal"]["snapshots"]
    assert [_value(row, "support_size") for row in snapshots] == [
        case["expected_snapshots"][version]["support_size"] for version in case["selected_versions"]]
    pairs = payload["derived_metrics"]["longitudinal"]["comparisons"]
    assert len(pairs) == 2
    for pair in pairs:
        for name in ("record_count_delta", "support_delta", "provenance_row_coverage_delta",
                     "direct_closure_lower_bound_delta"):
            assert pair[name]["status"] == "unavailable" and _value(pair, name) is None
            assert "R_LONGITUDINAL_PAIR_BLOCKED" in pair[name]["reason_codes"]


def test_incomplete_directed_mapping_retains_declaration_and_blocks_comparison(tmp_path):
    case = _case("directed_many_to_one")
    del case["expected_pairs"][0]["mapping"]["state_mapping"]["red"]
    report, _, _ = _report(case, tmp_path, tail=True)
    payload = _checked(report)
    pair = payload["inputs"]["longitudinal"]["comparisons"][0]
    assert pair["mapping"]["entries"]["total_count"] == 2
    assert pair["compatibility_status"] == "unavailable"
    assert pair["harmonized_basis_id"] is None and pair["mapping_collisions"] is None
    observed = payload["observed_facts"]["longitudinal"]["snapshots"]
    assert [_value(row, "record_count") for row in observed] == [4, 4]
    metrics = payload["derived_metrics"]["longitudinal"]["comparisons"][0]
    for name, envelope in metrics.items():
        if name == "comparison_id":
            continue
        assert envelope["status"] == "unavailable" and envelope["value"] is None
    for name in ("record_count_delta", "support_delta", "provenance_row_coverage_delta",
                 "source_type_share_deltas", "direct_closure_lower_bound_delta"):
        assert "R_LONGITUDINAL_PAIR_BLOCKED" in metrics[name]["reason_codes"]
    assert payload["capabilities"]["dataset_longitudinal"]["longitudinal_execution"]["status"] == "failed"
    view = privacy_view(report, mode="redacted", protection=IdentifierProtection(secret=SECRET))
    _checked(view)
    assert render_markdown(view) and render_json(view)


def test_hero_series_addition_preserves_ordinary_scientific_families():
    hero = ROOT / "examples/hero"
    bundle = validate_bundle(AuditBundle((
        InputSource(FileRole.RECORDS_PRIMARY, hero / "records_v2.csv"),
        InputSource(FileRole.RECORDS_COMPARE, hero / "records_v1.csv"),
        InputSource(FileRole.PROVENANCE_MANIFEST, hero / "provenance.csv"),
        InputSource(FileRole.VERSION_ORDER, hero / "version_order.json"))))
    config = RepresentationConfig(name="topic", source="topic_field", field="topic",
                                  version="hero-topic-v1", missing_value_policy="exclude")
    declarations = tuple(series.SnapshotDeclaration(version, config, "Hero literal topics") for version in ("v1", "v2"))
    selection = series.select_longitudinal_versions(bundle, declarations=declarations)
    result = series.analyze_longitudinal(bundle, selection=selection, lineage=True)
    kwargs = {"distributions": tuple(row.distribution for row in result.snapshots),
              "provenance": result.snapshots[-1].provenance,
              "closure": result.snapshots[-1].direct_closure,
              "comparison": result.comparisons[0].support_comparison}
    ordinary = _checked(assemble_report(bundle, run=_run(), **kwargs))
    combined = _checked(assemble_report(bundle, run=_run(), longitudinal=result, **kwargs))
    for section in ("observed_facts", "derived_metrics", "proxy_signals", "simulations"):
        assert {key: value for key, value in combined[section].items() if key != "longitudinal"} == {
            key: value for key, value in ordinary[section].items() if key != "longitudinal"}
    row = combined["derived_metrics"]["longitudinal"]["comparisons"][0]
    assert _value(row, "distinct_external_root_count_delta") == -3
    assert _value(row, "ancestry_concentration_hhi_delta") == 1 / 8
    assert _value(row, "effective_external_root_count_delta") == -4
    assert _value(row, "direct_closure_lower_bound_delta") == 1 / 2


@pytest.mark.parametrize("record_id_mode", ["hash", "omit"])
def test_redacted_mapping_joins_remain_basis_local_and_keys_never_leak(tmp_path, record_id_mode):
    case = _case("directed_many_to_one")
    labels = {label: "STATE_PRIVATE_" + label for label in ("red", "green", "pear", "apple")}
    for row in case["records"]:
        row["topic"] = labels[row["topic"]]
        row["content"] = "CONTENT_PRIVATE_SENTINEL"
    case["expected_pairs"][0]["mapping"]["state_mapping"] = {
        labels[source]: labels[target] for source, target in case["expected_pairs"][0]["mapping"]["state_mapping"].items()}
    for declaration in case["representations"].values():
        declaration["state_semantics"] += " MEANING_PRIVATE_SENTINEL"
    report, _, _ = _report(case, tmp_path, tail=True)
    original = _checked(report)
    view = privacy_view(report, mode="redacted", record_id_mode=record_id_mode,
                        protection=IdentifierProtection(secret=SECRET))
    protected = _checked(view)
    wire, markdown = render_json(view), render_markdown(view)
    assert "STATE_PRIVATE_" not in wire + markdown
    assert "CONTENT_PRIVATE_SENTINEL" not in wire + markdown
    assert "MEANING_PRIVATE_SENTINEL" not in wire + markdown
    assert str(tmp_path) not in wire + markdown
    inputs = protected["inputs"]["longitudinal"]
    assert all(row["state_semantics"] is None for row in inputs["representations"])
    descriptor = inputs["comparisons"][0]
    entries = descriptor["mapping"]["entries"]
    row = protected["derived_metrics"]["longitudinal"]["comparisons"][0]
    assert _value(row, "support_delta") == 0
    if record_id_mode == "omit":
        assert entries["items"] is None and entries["total_count"] == 3
        assert all(snapshot["dataset_version"] is None and snapshot["redaction"] for snapshot in inputs["snapshots"])
        assert _value(row, "retained_states")["items"] is None
    else:
        original_entries = original["inputs"]["longitudinal"]["comparisons"][0]["mapping"]["entries"]["items"]
        mapped = {source["source_state"]: target for source, target in zip(original_entries, entries["items"], strict=True)}
        pear = mapped[labels["pear"]]
        assert pear["source_state"] != pear["target_state"]
        assert mapped[labels["red"]]["target_state"] == mapped[labels["green"]]["target_state"]
        assert set(_value(row, "retained_states")["items"]) == {entry["target_state"] for entry in entries["items"]}
        collision = descriptor["mapping_collisions"]["items"][0]
        assert collision["target_state"] == mapped[labels["red"]]["target_state"]
        assert set(collision["source_states"]["items"]) == {
            mapped[labels["red"]]["source_state"], mapped[labels["green"]]["source_state"]}


def test_redacted_versions_join_context_and_retained_chronology(tmp_path):
    case = _case("lexical_order_context_unloaded")
    versions = {version: "VERSION_PRIVATE_" + version for version in case["order_document"]["version_order"]}
    def rename(value):
        if type(value) is str:
            return versions.get(value, value)
        if type(value) is list:
            return [rename(item) for item in value]
        if type(value) is dict:
            return {versions.get(key, key): rename(item) for key, item in value.items()}
        return value
    case = rename(case)
    report, _, _ = _report(case, tmp_path)
    original = _checked(report)
    view = privacy_view(report, mode="redacted", protection=IdentifierProtection(secret=SECRET))
    protected = _checked(view)
    version_map = dict(zip(original["inputs"]["version_order"], protected["inputs"]["version_order"], strict=True))
    descriptors = protected["inputs"]["longitudinal"]["snapshots"]
    assert [row["dataset_version"] for row in descriptors] == [version_map[version] for version in case["selected_versions"]]
    context = protected["inputs"]["longitudinal"]["context_versions"]
    assert context["items"] == [version_map[version] for version in sorted(case["context_versions"])]
    assert "VERSION_PRIVATE_" not in render_json(view) + render_markdown(view)
    assert [row["snapshot_id"] for row in descriptors] == ["s0001", "s0002"]


def test_standard_markdown_keeps_state_literals_inert(tmp_path):
    case = _case()
    label = "<script>alert(1)</script>|`STATE\u202e"
    for row in case["records"]:
        if row["topic"] == "B":
            row["topic"] = label
    report, _, _ = _report(case, tmp_path, tail=True)
    view = privacy_view(report, protection=IdentifierProtection(secret=SECRET))
    markdown = render_markdown(view)
    assert label not in markdown and "<script>" not in markdown
    assert "\\u003cscript\\u003e" in markdown and "\\u007c" in markdown
    assert "\\u0060" in markdown and "\\u202e" in markdown
    assert label in json.loads(render_json(view))["derived_metrics"]["longitudinal"]["comparisons"][0]["extinct_states"]["value"]["items"]


@pytest.mark.parametrize("source_count,target_count", [(102, 1), (204, 102)])
def test_mapping_and_each_collision_level_obey_detail_cap(tmp_path, source_count, target_count):
    case = _case("directed_many_to_one")
    states = {f"SOURCE_{index:03}": f"TARGET_{index % target_count:03}" for index in range(source_count)}
    case["records"] = [{"dataset_version": version, "record_id": f"record_{index:03}",
                        "topic": state, "content": "bounded mapping fixture"}
                       for version, values in (("v1", states), ("v2", sorted(set(states.values()))))
                       for index, state in enumerate(values)]
    case["provenance"] = [{"dataset_version": row["dataset_version"], "record_id": row["record_id"],
        "source_type": "synthetic", "provenance_confidence": "confirmed", "external_grounding": "no",
        "parent_ids": [], "transformation": "generate"} for row in case["records"]]
    case["expected_pairs"][0]["mapping"]["state_mapping"] = states
    report, _, _ = _report(case, tmp_path)
    payload = _checked(report)
    pair = payload["inputs"]["longitudinal"]["comparisons"][0]
    entries, collisions = pair["mapping"]["entries"], pair["mapping_collisions"]
    assert entries["limit"] == entries["returned_count"] == 100
    assert entries["total_count"] == source_count and entries["omitted_count"] == source_count - 100
    assert collisions["total_count"] == target_count
    assert collisions["returned_count"] == min(target_count, 100)
    for group in collisions["items"]:
        sources = group["source_states"]
        assert sources["total_count"] == source_count // target_count
        assert sources["returned_count"] == min(source_count // target_count, 100)
        assert sources["omitted_count"] == sources["total_count"] - sources["returned_count"]
    metrics = payload["derived_metrics"]["longitudinal"]["comparisons"][0]
    assert _value(metrics, "support_retention_ratio") == 1
    assert _value(metrics, "support_delta") == 0
    for mode in ("hash", "omit"):
        view = privacy_view(report, mode="redacted", record_id_mode=mode,
                            protection=IdentifierProtection(secret=SECRET))
        safe = _checked(view)
        assert "SOURCE_" not in render_json(view) and "TARGET_" not in render_markdown(view)
        protected = safe["inputs"]["longitudinal"]["comparisons"][0]["mapping"]["entries"]
        assert protected["total_count"] == source_count
